'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SpectrumLabLogFolder() As String
            Get
                Return CType(Me("SpectrumLabLogFolder"),String)
            End Get
            Set
                Me("SpectrumLabLogFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property ChartOutputFolderRoot() As String
            Get
                Return CType(Me("ChartOutputFolderRoot"),String)
            End Get
            Set
                Me("ChartOutputFolderRoot") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Column1Check() As Boolean
            Get
                Return CType(Me("Column1Check"),Boolean)
            End Get
            Set
                Me("Column1Check") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Column2Check() As Boolean
            Get
                Return CType(Me("Column2Check"),Boolean)
            End Get
            Set
                Me("Column2Check") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Column3Check() As Boolean
            Get
                Return CType(Me("Column3Check"),Boolean)
            End Get
            Set
                Me("Column3Check") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Column4Check() As Boolean
            Get
                Return CType(Me("Column4Check"),Boolean)
            End Get
            Set
                Me("Column4Check") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Column5Check() As Boolean
            Get
                Return CType(Me("Column5Check"),Boolean)
            End Get
            Set
                Me("Column5Check") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Column6Check() As Boolean
            Get
                Return CType(Me("Column6Check"),Boolean)
            End Get
            Set
                Me("Column6Check") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("22.2 kHz")>  _
        Public Property Column1Name() As String
            Get
                Return CType(Me("Column1Name"),String)
            End Get
            Set
                Me("Column1Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Column2Name() As String
            Get
                Return CType(Me("Column2Name"),String)
            End Get
            Set
                Me("Column2Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Column3Name() As String
            Get
                Return CType(Me("Column3Name"),String)
            End Get
            Set
                Me("Column3Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Column4Name() As String
            Get
                Return CType(Me("Column4Name"),String)
            End Get
            Set
                Me("Column4Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Column5Name() As String
            Get
                Return CType(Me("Column5Name"),String)
            End Get
            Set
                Me("Column5Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Column6Name() As String
            Get
                Return CType(Me("Column6Name"),String)
            End Get
            Set
                Me("Column6Name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ActivateSSRTonline() As Boolean
            Get
                Return CType(Me("ActivateSSRTonline"),Boolean)
            End Get
            Set
                Me("ActivateSSRTonline") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property VLFStationName() As String
            Get
                Return CType(Me("VLFStationName"),String)
            End Get
            Set
                Me("VLFStationName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property VLFStationIndex() As String
            Get
                Return CType(Me("VLFStationIndex"),String)
            End Get
            Set
                Me("VLFStationIndex") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SSRT_FTPusername() As String
            Get
                Return CType(Me("SSRT_FTPusername"),String)
            End Get
            Set
                Me("SSRT_FTPusername") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property SSRT_FTPpassword() As String
            Get
                Return CType(Me("SSRT_FTPpassword"),String)
            End Get
            Set
                Me("SSRT_FTPpassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ActivateGOESCharting() As Boolean
            Get
                Return CType(Me("ActivateGOESCharting"),Boolean)
            End Get
            Set
                Me("ActivateGOESCharting") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-80")>  _
        Public Property Floor() As String
            Get
                Return CType(Me("Floor"),String)
            End Get
            Set
                Me("Floor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("White")>  _
        Public Property Column1Color() As Global.System.Drawing.Color
            Get
                Return CType(Me("Column1Color"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Column1Color") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Lime")>  _
        Public Property Column2Color() As Global.System.Drawing.Color
            Get
                Return CType(Me("Column2Color"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Column2Color") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Yellow")>  _
        Public Property Column3Color() As Global.System.Drawing.Color
            Get
                Return CType(Me("Column3Color"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Column3Color") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Magenta")>  _
        Public Property Column4Color() As Global.System.Drawing.Color
            Get
                Return CType(Me("Column4Color"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Column4Color") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Orange")>  _
        Public Property Column5Color() As Global.System.Drawing.Color
            Get
                Return CType(Me("Column5Color"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Column5Color") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("OrangeRed")>  _
        Public Property Column6Color() As Global.System.Drawing.Color
            Get
                Return CType(Me("Column6Color"),Global.System.Drawing.Color)
            End Get
            Set
                Me("Column6Color") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MidnightBlue")>  _
        Public Property SIDChartTopColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("SIDChartTopColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("SIDChartTopColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MediumBlue")>  _
        Public Property SIDChartBottomColor() As Global.System.Drawing.Color
            Get
                Return CType(Me("SIDChartBottomColor"),Global.System.Drawing.Color)
            End Get
            Set
                Me("SIDChartBottomColor") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Column1Offset() As String
            Get
                Return CType(Me("Column1Offset"),String)
            End Get
            Set
                Me("Column1Offset") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Column2Offset() As String
            Get
                Return CType(Me("Column2Offset"),String)
            End Get
            Set
                Me("Column2Offset") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Column3Offset() As String
            Get
                Return CType(Me("Column3Offset"),String)
            End Get
            Set
                Me("Column3Offset") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Column4Offset() As String
            Get
                Return CType(Me("Column4Offset"),String)
            End Get
            Set
                Me("Column4Offset") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Column5Offset() As String
            Get
                Return CType(Me("Column5Offset"),String)
            End Get
            Set
                Me("Column5Offset") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Column6Offset() As String
            Get
                Return CType(Me("Column6Offset"),String)
            End Get
            Set
                Me("Column6Offset") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property LogFileFolder() As String
            Get
                Return CType(Me("LogFileFolder"),String)
            End Get
            Set
                Me("LogFileFolder") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property StationTitle() As String
            Get
                Return CType(Me("StationTitle"),String)
            End Get
            Set
                Me("StationTitle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property VLFStationKey() As String
            Get
                Return CType(Me("VLFStationKey"),String)
            End Get
            Set
                Me("VLFStationKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property Ceiling() As String
            Get
                Return CType(Me("Ceiling"),String)
            End Get
            Set
                Me("Ceiling") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SSRT_Robot.My.MySettings
            Get
                Return Global.SSRT_Robot.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
